### ISSUE TITLE
Error cloning repository

### ISSUE THREAD

**Issue by ciror00** [Parrot-Developers/groundsdk-manifest#5]
Hi!

I am following the SDK installation steps. When i do step [clone workspace](https://developer.parrot.com/docs/olympe/installation.html#clone-the-parrot-groundsdk-repo-workspace), it shows me the following error:
```
$ repo init -u https://github.com/Parrot-Developers/groundsdk-manifest.git
Traceback (most recent call last):
  File "/home/ciro/code/parrot-groundsdk/.repo/repo/main.py", line 56, in <module>
    from subcmds.version import Version
  File "/home/ciro/code/parrot-groundsdk/.repo/repo/subcmds/__init__.py", line 38, in <module>
    ['%s' % name])
  File "/home/ciro/code/parrot-groundsdk/.repo/repo/subcmds/upload.py", line 27, in <module>
    from hooks import RepoHook
  File "/home/ciro/code/parrot-groundsdk/.repo/repo/hooks.py", line 472
    file=sys.stderr)
        ^
SyntaxError: invalid syntax
```
Can anybody help me?

**Comment by dominiknatter** [comment]
Hi @ciror00,

I face the same problems. I have a running Olympe system on my laptop which was installed about 6 months ago. Now I want to install a second one on another laptop. However, exactly when running the `repo init ...` command I get this error.

After some research it sounds to me like the SyntaxError is caused when you call print('...', file=sys.stderr) from Python 2. So apparently repo is running the main.py with Python 2.x, even though the shebang says Python3. Even if this is a correct analysis, I was not able to find a solution yet.

Maybe someone from Parrot knows better what has changed in the most recent commits?

Thanks in advance!

**Comment by dominiknatter** [comment]
Hi everyone,
by accident I figured out that 
`repo init -u https://github.com/Parrot-Developers/groundsdk-manifest.git`
can be replaced by
`./.repo/repo/repo init -u https://github.com/Parrot-Developers/groundsdk-manifest.git`
Or maybe one needs to run `repo init` first in order to get the hidden folder `.repo` into the folder `~/code/parrot-groundsdk`.
Subsequently, replace
`repo sync`
by
`./.repo/repo/repo sync`.

For me at least it finished without an error and I was able to continue and complete the Olympe installation.

**Comment by ValerioJiang** [comment]
> Hi everyone,
> by accident I figured out that
> `repo init -u https://github.com/Parrot-Developers/groundsdk-manifest.git`
> can be replaced by
> `./.repo/repo/repo init -u https://github.com/Parrot-Developers/groundsdk-manifest.git`
> Or maybe one needs to run `repo init` first in order to get the hidden folder `.repo` into the folder `~/code/parrot-groundsdk`.
> Subsequently, replace
> `repo sync`
> by
> `./.repo/repo/repo sync`.
> 
> For me at least it finished without an error and I was able to continue and complete the Olympe installation.

Thanks man, i resolved this issue otherwise impossible to figure it out the solution :)
